#!/usr/bin/ksh

# Clone a new version of tds and checkout a branch

if [ $# -eq 0 ]; then
  echo "Specify a directory name to clone the repository into"
  exit 1;
fi

if [ $# -eq 1 ]; then
  echo "Specify a branch to checkout. Don't do development on the master branch";
  exit 1;
fi

if [ $# -ge 3 ]; then
  echo "Too many arguments were passed to this command"
  exit 1;
fi

# Clone and rename directory to $1
git clone git@fc9pftdsp05.usgfoundries.com:TestDataSystemDev/orangeTds.git $1

# Checkout branch $2 and create it if it doesn't exist
cd $1
git checkout -B $2
cd ..
