#!/bin/bash

if [[ $# != 1 ]]; then
  echo "Please Provide A Make Target"
  return
fi

directory=$(git rev-parse --show-toplevel)
buildlog=$directory/build.log
builderr=$directory/build.err
recipe=$1

echo "Making Recipe: $recipe"
make -C $directory $recipe > $buildlog 2> $builderr
make_rc=$?

echo ""
echo "---- Listing Built Objects ----"
echo ""

grep -i made $buildlog

errors=$(grep -i error $builderr)

if [[ ! -z $errors ]]; then
  echo ""
  echo "---- Listing Build Errors ----"
  echo ""

  echo $errors
fi

exit $make_rc
