#!/usr/bin/sh
# Used for creating a nice look for the TDS build process

make_recipe=${@:-all}
dir=$(pwd)

build_log=$dir/build.log
build_err=$dir/build.err

RED='\e[1;31m'
YELLOW='\e[0;33m'
NC='\e[0m'

function echoFlag() {
  echo -e "\n--- $1 ---\n"
}

# Not currently implemented
function colorOutput() {
  read buildobj
  search='(Made)(.*)'
  substitute="${RED}\\1${YELLOW}\\2${NC}"
  set -x
  colored_str=$(echo $buildobj | sed -e "s/$search/$substitute/")
  set +x
  echo -e $colored_str
}

echo -e "${RED}Building Recipe ${YELLOW}$make_recipe${NC}"
echoFlag 'Listing Built Objects'

# Make and output build sections as they happen
make $make_recipe 2> $build_err | tee $build_log | grep --color Made
make_rc=${PIPESTATUS[0]}

if [[ $make_rc != 0 ]]; then
  errors=$(grep -i error $build_err)
  echoFlag "Listing Build Errors"
  echo "$errors"
fi

echo ''
exit $make_rc
