#!/usr/bin/env python3
'''
A static module generator for notes.
'''

from pathlib import Path
import markdown2


def main():
    '''
    Main entry point into the static website generator.
    '''
    note_directory = Path.home() / 'Notes'
    html_directory = Path.home() / 'public_html'

    print('Generating html pages for notes files...')
    print(str(note_directory))
    print(str(html_directory))

    if note_directory.is_dir():
        notes = note_directory.glob('**/*.md')

        for note_path in notes:
            html_path = html_directory / (note_path.stem + '.html')
            print(f'Converting {note_path} into {html_path}')
            convert(note_path, html_path)


def convert(markdown_path: Path, html_path: Path) -> None:
    '''
    Convert a markdown file into an html file.
    '''
    with markdown_path.open() as markdown, html_path.open('w') as html:
        markdown_content = '\n'.join(markdown.readlines())
        html_content = markdown2.markdown(markdown_content)
        html.write(html_content)


if __name__ == '__main__':
    main()
